### ISSUE TITLE
[Research] Better tiles for map at least 23-26 px

### ISSUE THREAD

**Issue by krutarth4** [Smoothex/parking-place-occupancy#21]
Need better map tiles as it distorts after certain level of Zooming as the maxZoom default is crossed and the map has enabled feature for force Zoom. This leads to Bug.

**Comment by krutarth4** [comment]
@gogokotsev00 @Smoothex  If you guys find anything let me know !!. For open Source map, we still have not that good sources

**Comment by Smoothex** [comment]
Hey @krutarth4 I did some digging:
* Bing Maps uses [ArcGis](https://www.arcgis.com/home/index.html) and seems to offer a good quality when zooming in:
![image](https://github.com/Smoothex/parking-place-occupancy/assets/79105432/28b54906-07fb-4e5c-b5f5-306f3bdf4482)
I am not how easy the integration is, but the [ArcGIS Docs](https://developers.arcgis.com/documentation/app-builders/low-code/tutorials/tools/integrate-arcgis-apps-in-exb/) can shed some light on this. 
* I also stumbled upon [Mapbox](https://www.mapbox.com/) which offers satellite view too with its [Mapbox Satellite](https://docs.mapbox.com/help/glossary/mapbox-satellite/) and the quality seems quite good too:
![image](https://github.com/Smoothex/parking-place-occupancy/assets/79105432/415f3908-f7df-4d51-b725-b92968fcd737)
Mapbox even has an [Angular integration](https://github.com/Naimikan/angular-mapboxgl-directive?tab=readme-ov-file) ([List of plugins and integrations](https://docs.mapbox.com/mapbox-gl-js/plugins/#framework-integrations)) and works with OpenStreetMap, which seems to fit our needs, doesn't it?
