### ISSUE TITLE
[frontend] REST edited polygon data object

### ISSUE THREAD

**Issue by krutarth4** [Smoothex/parking-place-occupancy#22]

**Comment by krutarth4** [comment]
The request for an edited polyline will be sent as 

@gogokotsev00 you can decide for which endpoint it should go to for editing polygon

and in request body a key value pair will be given 

body = {
geometry: new_geometry
} 

the new geometry is an array as described below .



new_gerometry=
[
  {
    "lat": 52.54417090700516,
    "lng": 13.355445691050301
  },
  {
    "lat": 52.54413597987759,
    "lng": 13.355369757344532
  },
  {
    "lat": 52.544132412189335,
    "lng": 13.355358416476323
  },
  {
    "lat": 52.54412547616992,
    "lng": 13.35534328827827
  },
  {
    "lat": 52.54414381143567,
    "lng": 13.35532056504905
  },
  {
    "lat": 52.54419020037736,
    "lng": 13.35542154095254
  }
]

**Comment by krutarth4** [comment]
the data is now consistent with the data 


[
  [
    13.35415206329387,
    52.543614778526965
  ],
  [
    13.354036145909681,
    52.543568313273695
  ],
  [
    13.354014469532968,
    52.54358866922784
  ],
  [
    13.354130265411584,
    52.543635086205796
  ]
]

**Comment by gogokotsev00** [comment]
@krutarth4 you will have to add one pair of square brackets outside the JSON response in your latest comment like this `[[[x,y], [x,y],...]]`
